# Generated by Django 4.2.13 on 2024-05-20 14:47

import ckeditor.fields
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
